-- ===========================================================================
-- Public storage bucket for admin-managed listing images
-- (properties / projects / plots). Uploaded from the admin dashboard; the
-- object's public URL is stored in the row's image / gallery columns and shown
-- on the public site.
--
-- Uploads are performed with short-lived SIGNED UPLOAD URLs generated by the
-- service role inside an admin-guarded server action, so only the admin can add
-- images even though the bucket is publicly readable.
-- ===========================================================================

insert into storage.buckets (id, name, public)
values ('listing-images', 'listing-images', true)
on conflict (id) do nothing;

-- Public read (bucket is public; explicit policy for clarity).
drop policy if exists "public read listing images" on storage.objects;
create policy "public read listing images" on storage.objects
  for select to anon, authenticated
  using (bucket_id = 'listing-images');
